#' printDecisionTree
#'
#' print a DecisionTreeObject
#' @param DecisionTreeObject object of class DecisionTreeObject generated by function decisionTree
#' @keywords print decision tree, decision tree
#' @export

print.DecisionTreeObject <- function(DecisionTreeObject) {
  print(DecisionTreeObject@resultDF)
}

